---
title: "Other_clustering"
author: "Gabriel Burcea"
date: "07/09/2020"
output: word_document
---


Loading in the libraries needed 

```{r}
library(tidyverse)
library(cluster)
library(plotly)
library(fpc)
library(dendextend)
library(factoextra)
library(FactoMineR)
library(NbClust)
library(caret)
library(DMwR)
library(qgraph)
library(igraph)
```


Read in the data and process accordingly. 

```{r}


data_cluster <- read_csv("/Users/gabrielburcea/rprojects/data/your.md/cleaned_data_18_08_2020_fully_cleaned_uniq_comorb.csv")


data_select <- data_cluster %>%
  dplyr::select(id, age, gender, covid_tested, chills, cough, diarrhoea, fatigue, headache, loss_smell_taste, muscle_ache, 
                nasal_congestion, nausea_vomiting, shortness_breath, sore_throat, sputum, temperature, loss_appetite, chest_pain, itchy_eyes, joint_pain, 
                asthma, diabetes_type_one, diabetes_type_two, obesity, hypertension, heart_disease, lung_condition, liver_disease, kidney_disease) %>%
  dplyr::filter(covid_tested != "negative") 


covid_tested_levels <- c("positive" = "showing symptoms")

data_transf <- data_select %>% 
  dplyr::mutate(covid_tested = forcats::fct_recode(covid_tested, !!!covid_tested_levels))


data_piv<- data_transf %>%
  pivot_longer(cols = 22:30, 
               names_to = "comorbidities",
               values_to = "Bolean") %>%
  dplyr::filter(Bolean != "No")

data_piv_id <- dplyr::mutate(data_piv, respondents_id = rownames(data_piv))

data_clean <- data_piv_id %>%
  dplyr::select(respondents_id, comorbidities, chills, cough, diarrhoea, fatigue, headache, loss_smell_taste, muscle_ache, 
                nasal_congestion, nausea_vomiting, shortness_breath, sore_throat, sputum, temperature, loss_appetite, chest_pain, itchy_eyes, joint_pain ) %>%
  drop_na()


#data_rec <- ifelse(data_piv_id[,3:19] == "Yes", 1,0)
#data_clean <- cbind(data_piv_id[,1:2], data_rec)

data_clean$chills <- as.factor(data_clean$chills)
data_clean$cough <- as.factor(data_clean$cough)
data_clean$diarrhoea <- as.factor(data_clean$diarrhoea)
data_clean$fatigue <- as.factor(data_clean$fatigue)
data_clean$headache <- as.factor(data_clean$headache)
data_clean$loss_smell_taste <- as.factor(data_clean$loss_smell_taste)
data_clean$muscle_ache <- as.factor(data_clean$muscle_ache)
data_clean$ nasal_congestion <- as.factor(data_clean$ nasal_congestion)
data_clean$nausea_vomiting <- as.factor(data_clean$nausea_vomiting)
data_clean$shortness_breath <- as.factor(data_clean$shortness_breath)
data_clean$sore_throat <- as.factor(data_clean$sore_throat)
data_clean$sputum <- as.factor(data_clean$sputum)
data_clean$temperature <- as.factor(data_clean$temperature)
data_clean$loss_appetite <- as.factor(data_clean$loss_appetite)
data_clean$chest_pain <- as.factor(data_clean$chest_pain)
data_clean$itchy_eyes <- as.factor(data_clean$itchy_eyes)
data_clean$joint_pain <- as.factor(data_clean$joint_pain)
data_clean <- as.data.frame(data_clean)

rownames(data_clean) <- data_clean$respondents_id

```




```{r}

data_count <- data_clean %>% 
  pivot_longer(cols = 3:19,
             names_to = "symptoms",
             values_to = "yes_no")  %>%
  dplyr::group_by(comorbidities, symptoms, yes_no) %>%
  dplyr::summarise(Count = n()) %>%
  dplyr::mutate(Freq = Count / sum(Count)*100) %>%
  dplyr::filter(yes_no == "Yes") %>%
  dplyr::select(comorbidities, symptoms, Freq)


dt_wd <- data_count %>% 
  tidyr::pivot_wider(names_from = "symptoms", values_from = "Freq")

dt_wd <- as.data.frame(dt_wd)
dt_wd$comorbidities<- as.character(dt_wd$comorbidities)


rownames(dt_wd) <- dt_wd$comorbidities

```



Create a list with methods of clustering. 
```{r}

hclust_methods <- c("ward.D", "single", "complete", "average", "mcquitty", 
        "median", "centroid", "ward.D2")

dt_wd_sympt <- dt_wd[,2:18]

dist_sympt <- dist(dt_wd_sympt, method = "euclidean")

sympt_dendlist <- dendlist()

sympt_dendlist

for(i in seq_along(hclust_methods)){
  hc_sympt <- hclust(dist_sympt, method = hclust_methods[i])
  
  sympt_dendlist <- dendlist(sympt_dendlist, as.dendrogram(hc_sympt))
}


names(sympt_dendlist) <- hclust_methods
sympt_dendlist


hclust_methods
```

Loiking at the cophenetic correlation between each clsutering result

```{r}

sympt_dendlist_cor <- cor.dendlist(sympt_dendlist)

sympt_dendlist_cor

```

```{r}
corrplot::corrplot(sympt_dendlist_cor, "pie", "lower")
```

```{r}
hclust_methods
```


other types of data viz 

```{r}

dt_sympt <- dt_wd[,-1]

comorbid_labels <- dt_wd[,1]
comorbid_labels

###############################################
#### Euclidean distance #######################
###############################################
dt_sympt <- dist(dt_sympt, method = "euclidean")

hc_sympt <- hclust(dt_sympt, method = "ward")

library(dendextend)

dend <- as.dendrogram(hc_sympt)


gplots::heatmap.2(as.matrix(dt_sympt), 
                  main = "Heatmap: Cluster of comorbidities based on Covid-19 Symptoms", 
                  dendogram = row, 
                  Rowv = dend) 



```




```{r}
dend_list <- dendlist(dend_complete, dend_ward)

tanglegram(dend_complete, dend_ward, 
           margin_inner = 10,
           highlight_distinct_edges = FALSE, #Turn-off dashed line
           common_subtrees_color_lines = TRUE, # Turn-off line colors
           common_subtrees_color_branches = TRUE, # Color common branches
           main = paste("entanglement =", round(entanglement(dend_list),2)))

```




As we compare the two dendograms, the entanglement coefficient is 0. This tells us it is a good alignment. 
```{r}

# Compute distance matrix
res_dist <- dist(dt_wd, method = "euclidean")

# Compute 2 hierarchical clusterings
hc_complete <- hclust(res_dist, method = "complete")
hc_ward <- hclust(res_dist, method = "ward.D2")

# Create two dendrograms
dend_complete <- as.dendrogram (hc_complete)
dend_ward <- as.dendrogram (hc_ward)


```



